name: traffic_monitoring
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24.4
  - scipy=1.10.1
  - matplotlib=3.7.2
  - pandas=2.0.3
  - pillow=10.0.1
  - pyyaml=6.0.1
  - requests=2.31.0
  - tqdm=4.66.1
  - psutil=5.9.5
  - sqlalchemy=2.0.21
  - pytest=7.4.2
  - opencv=4.8.1
  - pytorch=2.0.1
  - torchvision=0.15.2
  - cpuonly  # Remove for CUDA support
  - pip
  - pip:
    - PyQt5==5.15.9
    - ultralytics==8.0.196
    - alembic==1.12.0
    - colorlog==6.7.0
    - imageio==2.31.3
    - imageio-ffmpeg==0.4.9
    - pytest-cov==4.1.0
